### PR TITLE
fix(properties.json): BaseWithNumericId#idNumeric is of type Integer now

### PR DESCRIPTION
**Pull request by felixlinker**

### CODE REVIEW

**Comment by philippfromme** [comment]
There are two things:

* Linting tests fail on [Travis](https://travis-ci.org/bpmn-io/moddle/builds/263862913?utm_source=github_status&utm_medium=notification)
* Can you explain a bit further what changes you made and what the reasoning behind those is?

**Comment by felixlinker** [comment]
Oh! I didn't intend to merge the whole master branch. I only wanted to merge my first `fix` commit. Still new to opening up pull-requests on GitHub.

Anyways, as you have asekd, I can quickly explain the two main features I added.

1. I added type-checks to all `Base#set` aka `Properties#set` calls.
2. I added the possibility to constrain any built-in property that is not of type `Element` (i. e. `Integer`, `Real`, `String`, `Boolean`) in three ways: You can constrain them by a regex expression (`constraint: { regex: '...' }`), by a list of possible values (`constraint: { enum: [ ... ] }`) or by a [mathjs-Expression](http://mathjs.org/docs/expressions/index.html) (`constraint: { math: '...' }`

If you're generally interested in that kind of functionality, I can keep the PR open. Otherwise I'd re-request my fix made in the first commit.

**Comment by philippfromme** [comment]
We always welcome PRs so if that's okay just open a second PR for the other changes you made and we'll look into this. 😉

**Comment by felixlinker** [comment]
Sure thing, I have the two features split up in branches anyways.

**Pull request closed without merging**
