### PR TITLE
Provide JSON schema for moddle

### LINKED ISSUE #62: Provide JSON schema for moddle (including XML extension elements)
### Is your feature request related to a problem? Please describe.

As a developer, I want to make sure that my moddle schema instance is checked against a moddle schema definition and any violations are reported by a standard schema validation tool.

### Describe the solution you'd like

Provide a complete JSON schema. The parts references in docs folder are helpful, but incomplete.

### Describe alternatives you've considered

None

### Additional context

I developed a JSON schema and would like you to double check it and include into this repository.

### PR DESCRIPTION
**Pull request by zambrovski**
### Proposed Changes

- provide JSON schema
- closes #62

### Checklist

To ensure you provided everything we need to look at your PR:

* [x] **Brief textual description** of the changes present
* [x] **Visual demo** attached
* [x] **Steps to try out** present, i.e. [using the `@bpmn-io/sr` tool](https://github.com/bpmn-io/sr)
* [x] Related issue linked via `Closes {LINK_TO_ISSUE}` or `Related to {LINK_TO_ISSUE}`

### CODE REVIEW

**Comment by barmac** [comment]
How would you compare this with existing schema in https://github.com/bpmn-io/moddle/blob/main/docs/moddle.json?

**Comment by zambrovski** [comment]
Done

**Comment by barmac** [comment]
Thanks. I'm afraid I may not be able to review the PR this week, but will look into this at latest beginning next week.

**Comment by barmac** [comment]
Thanks for the contribution. I checked this schema with `ajv-cli` and while some warnings are printed, it still works correctly.

```
> npx ajv-cli -s docs/moddle.json -d /Users/maciej/workspace/bpmn-io/moddle/test/fixtures/model/meta.json
strict mode: missing type "object" for keyword "required" at "https://bpmn.io/20241206/moddle-package.schema.json#/properties/types/items" (strictTypes)
strict mode: missing type "object" for keyword "properties" at "https://bpmn.io/20241206/moddle-package.schema.json#/properties/types/items" (strictTypes)
strict mode: missing type "object" for keyword "properties" at "https://bpmn.io/20241206/moddle-package.schema.json#/properties/types/items/properties/properties/items" (strictTypes)
strict mode: use allowUnionTypes to allow union type keyword at "https://bpmn.io/20241206/moddle-package.schema.json#/properties/types/items/properties/properties/items/properties/default" (strictTypes)
strict mode: missing type "object" for keyword "properties" at "https://bpmn.io/20241206/moddle-package.schema.json#/properties/enumerations/items/properties/literalValues/items" (strictTypes)
```

I used this schema to verify all schemas maintained at bpmn-io and camunda, and this allowed to detect a typo in camunda-bpmn(dmn)-moddle libraries: `emumerations`.

What is still missing to complete the story is some form of documentation, and a test case.

> I made this schema very restrictive (`additionalAttributes` is set to false) and imported it as a schema definition to bpmn-moddel to deouble-check that nothing (undocumented) is missing.

I would also remove this property as this prevents developers from adding some form of meta information to their schemas. As long as the additional properties don't break `moddle`, they should be allowd.

**Comment by barmac** [comment]
> a test case

I've added a test for all fixtures.

**Comment by barmac** [comment]
Thanks for your contribution @zambrovski! This is merged now.

**Comment by nikku** [comment]
Proposal: As a follow-up we move the schema to the `resources` directory, cf. [bpmn-moddle](https://github.com/bpmn-io/bpmn-moddle/tree/main/resources).

I'd also update the example, to consume from a CDN instead, using the `$schema` attribute, i.e.:

```json
{
  "$schema": "https://unpkg....",
  "parts": "of",
  "my": "moddle",
  "schema": true
}
```

**Comment by nikku** [comment]
Proposed follow-up: https://github.com/bpmn-io/moddle/pull/64.

**Pull request merged**
